### ISSUE TITLE
Hide the monitor label when only a single monitor is plugged in

### ISSUE THREAD

**Issue by ChausseBenjamin** [flaport/dwm#2]
Your setup is awesome dude! 
The mastermonitor patch is exactly what I needed.
I was just wondering how you can get the monitor number to be hidden
when you are using a single monitor...
Also, I couldn't figure out how you managed to change the master monitor
to another monitor.

**Comment by flaport** [comment]
Nice to see you're liking my setup.

To be honest, lots of it has grown quite organically and I forgot how I exactly implemented most of it. Just note that the mastermonitor patch at commit `55a46c0` is definitely out of date and a lot of changes have been made on the master branch of this repo to remove bugs and improve general behavior. Unfortunately, these changes are mingled in with the other patches and hence are quite difficult to track.

To answer your first question, the monitor number (tag) is drawn in the function `drawbar`:
```
	x = drw_text(drw, x, 0, w, bh, lrpad / 2, montags[m->num], 0);
```
Note that the variable `mons` points tot he first monitor. The next monitor can be accessed with `mons->next`, hence if that one does not exist it's fairly easy to encode different behavior.

If I find some time the next few days, I'll try to implement it myself. Otherwise, feel free to make a pull request ;-)

Your second question is more complicated though, essentially it comes down to setting `mastermon` equal to `selmon`:
```
    mastermon = selmon;
```
and for the longest time, this was the only implementation I had, however this has the problem that the new `mastermon` still has its own set of tags, essentially hiding the tags of the old mastermon (except tag 1). This is most likely not what you want, hence the fairly complicated `setmastermon` function that swaps the tags around as well.

**Comment by flaport** [comment]
FYI, @ChausseBenjamin , monitor labels are now hidden by default for single monitor setups. Also, I did some effort to better separate the different patches I applied in the build (have a look in the [readme](https://github.com/flaport/dwm)). A better mastermonitor patch can now be downloaded [here](https://github.com/flaport/dwm/compare/upstream..mastermon.diff).

**Comment by ChausseBenjamin** [comment]
Wow! Your work is amazing!
Thank you for everything which you are contributing.
